spring.application.name=image

# S3
aws.s3.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_BUCKET_NAME}
aws.s3.endpoint=${AWS_S3_ENDPOINT}

# H2
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect